# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dataframe": "00_utils.ipynb",
         "get_test_dataframe": "00_utils.ipynb",
         "ClassificationInterpretation.plot_roc": "00_utils.ipynb",
         "field_bias_correction": "01_preprocessing.ipynb",
         "denoising": "01_preprocessing.ipynb",
         "clip_tail": "01_preprocessing.ipynb",
         "hist_matching": "01_preprocessing.ipynb",
         "Pipeline": "01_preprocessing.ipynb",
         "preprocessing_pipeline": "01_preprocessing.ipynb",
         "TorchIOTransform": "02_augment.ipynb",
         "TioTransforms": "02_augment.ipynb",
         "TioRandomBiasField": "02_augment.ipynb",
         "TioRandomGhosting": "02_augment.ipynb",
         "TioRandomMotion": "02_augment.ipynb",
         "TioRandomGamma": "02_augment.ipynb",
         "TioRandomAnisotropy": "02_augment.ipynb",
         "TioRandomElasticDeformation": "02_augment.ipynb",
         "SequentialModel": "04_classification_models.ipynb"}

modules = ["utils.py",
           "preprocessing.py",
           "augment.py",
           "models.py"]

doc_url = "https://kbressem.github.io/"

git_url = "https://github.com/kbressem/spa/tree/master/"

def custom_doc_links(name): return None
